export const projects = [
  {
    id: 1,
    title: "pizza clone",
    img: "/images/pizza-clone.webp",
    url: "https://pizza-clone.vercel.app",
    technology: "next",
    aos: "fade-down",
  },
  {
    id: 2,
    title: "foodera",
    img: "/images/foodera.webp",
    url: "https://fooderaa.vercel.app",
    technology: "next",
    aos: "zoom-in",
  },

  {
    id: 3,
    title: "quraan player",
    img: "/images/quraan-player.webp",
    url: "https://quraan-player.vercel.app",
    technology: "next.js & fetch API",
    aos: "fade-down",
  },
  {
    id: 4,
    title: "Budget Tracker",
    img: "/images/budget-tracker.webp",
    url: "https://react-todo-list-murex-six.vercel.app",
    technology: "next.js & fetch API",
    aos: "fade-zoom",
  },
  {
    id: 5,
    title: "bondi",
    img: "/images/bondi.webp",
    url: "https://ahmed-khaled11.github.io/Bondi",
    technology: "bootstrap",
    aos: "zoom-in",
  },
  {
    id: 6,
    title: "template",
    img: "/images/template.webp",
    url: "https://ahmed-khaled11.github.io/Project-4",
    technology: "html",
    aos: "fade-up",
  },

  {
    id: 7,
    title: "memory game",
    img: "/images/memory-game.webp",
    url: "https://ahmed-khaled11.github.io/Memory-Game",
    technology: "game",
    aos: "zoom-in",
  },
  {
    id: 8,
    title: "type speed test game",
    img: "/images/typing-speed-test-game.webp",
    url: "https://ahmed-khaled11.github.io/Typing-Speed-Test-Game-V3",
    technology: "game",
    aos: "fade-right",
  },
];
